services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4343:4343"
    environment:
      - NODE_ENV=production
      - PORT=4343
    restart: unless-stopped
    container_name: vh-tt-danang-frontend 